services:
  fhir-tools:
    build:
      context: ./fhir-tools
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    networks:
      - mcp-network

  tx-tools:
    build:
      context: ./tx-tools
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge