name: "Test tx-tools"
on:
  push:
    paths:
      - "tx-tools/**"
  pull_request:
    paths:
      - "tx-tools/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: tx-tools
        run: bun install

      - name: Run linter
        working-directory: tx-tools
        run: bun run lint

      - name: Run tests
        working-directory: tx-tools
        run: bun run test
