name: "Test fhir-tools"
on:
  push:
    paths:
      - ".github/workflows/test-fhir-tools.yml"
      - "fhir-tools/**"
  pull_request:
    paths:
      - ".github/workflows/test-fhir-tools.yml"
      - "fhir-tools/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: fhir-tools
        run: bun install

      - name: Run linter
        working-directory: fhir-tools
        run: bun run lint

      - name: Check formatting
        working-directory: fhir-tools
        run: bun run format:check

      - name: Run tests
        working-directory: fhir-tools
        run: bun run test
